import { ArrowRight, ArrowUpRight, ChevronDown, Menu, Check } from "lucide-react";
import { useState } from "react";
import { useRoute } from "wouter";
import ServicesMegaMenu from "@/components/ServicesMegaMenu";
import SiteMegaMenu, { aboutItems, industryItems } from "@/components/SiteMegaMenu";

const aboutSections = [
  { slug: "company-overview", name: "Company Overview", title: "A consultancy built for meaningful progress.", intro: "Hill-Top Consultancy helps ambitious organizations turn technology challenges into durable business value through cloud, DevOps, data, AI, and software engineering.", body: "We work where strategy meets delivery. That means understanding the commercial goal, the people who need to change, the systems that already exist, and the operational standards that will determine whether an initiative lasts. Our teams bring senior judgment, practical engineering, and an explicit focus on knowledge transfer.", points: ["Senior practitioners close to the work", "Technology decisions connected to business outcomes", "Delivery plans built around evidence and iteration", "Capability transfer that keeps value in your organization"] },
  { slug: "leadership-team", name: "Leadership Team", title: "Experienced leaders who stay close to delivery.", intro: "Our leadership model combines strategic perspective with the practical discipline needed to make complex technology programs move.", body: "Hill-Top Consultancy is designed to keep decision-makers connected to the teams doing the work. Leaders set direction, remove friction, make trade-offs visible, and create the conditions for specialists to deliver their best work.", points: ["Clear accountability from discovery through operations", "Transparent decisions and visible trade-offs", "A culture of technical curiosity and candor", "Experienced guidance for high-stakes change"] },
  { slug: "industry-recognitions", name: "Industry Recognitions", title: "Progress measured by the quality of the work.", intro: "We are building a reputation through the outcomes we create, the standards we uphold, and the trust we earn with clients and partners.", body: "Recognition matters when it reflects meaningful practice: reliable delivery, responsible technology, strong teams, and measurable client value. This page is prepared for Hill-Top Consultancy awards, certifications, partner accreditations, and published achievements.", points: ["Technology and cloud certifications", "Client outcome stories and independent references", "Partner ecosystem accreditations", "Internal quality and security standards"] },
  { slug: "partnerships", name: "Partnerships", title: "Better outcomes through the right ecosystem.", intro: "We work across the platforms, tools, and specialist communities that modern teams already depend on.", body: "A strong partner ecosystem helps clients move faster without compromising fit or control. We bring together cloud platforms, data technologies, security practices, design capability, and delivery expertise around the context of each engagement.", points: ["Cloud and platform architecture alignment", "Practical integration and implementation support", "Shared delivery standards and enablement", "A vendor-neutral view of technology trade-offs"] },
  { slug: "clients", name: "Clients", title: "Long-term trust, earned one outcome at a time.", intro: "Our clients come to us when technology has to carry real operational, customer, or growth responsibility.", body: "We work with leaders and delivery teams across regulated, industrial, commercial, and technology-led environments. The work is different in every organization, but the expectation is consistent: clarity, accountability, and progress that can be seen in the real world.", points: ["Direct collaboration with client stakeholders", "Clear measures of progress and value", "Respect for existing teams and domain knowledge", "Delivery practices designed to build confidence"] },
  { slug: "careers", name: "Careers", title: "Do work you can be proud to leave behind.", intro: "Join a consultancy where craft, curiosity, and care for the outcome matter more than theatre.", body: "At Hill-Top Consultancy, people are trusted with meaningful problems and supported with the context to solve them well. We value clear thinking, kindness, technical depth, and the willingness to share what you learn. This page is prepared for open roles, hiring principles, and our candidate process.", points: ["Work on modern cloud and engineering challenges", "Learn alongside senior practitioners", "Own outcomes, not just tickets", "Build a career around durable skills"] },
  { slug: "news", name: "News", title: "What we are learning and building.", intro: "Updates from Hill-Top Consultancy, our clients, our partners, and the wider technology community.", body: "Our news section is intended to share launches, team milestones, technical perspectives, and useful lessons from delivery. We aim to publish information that is specific enough to help practitioners and clear enough for decision-makers.", points: ["Company announcements", "Technical perspectives", "Client and partner updates", "Community and team stories"] },
  { slug: "events", name: "Events", title: "Useful conversations for people doing the work.", intro: "Join us for practical conversations about cloud, DevOps, AI, security, and modern software delivery.", body: "We use events to create space for honest exchange: what is working, what is changing, and which assumptions deserve another look. This page is prepared for workshops, roundtables, webinars, and speaking engagements.", points: ["Executive briefings", "Engineering workshops", "Community roundtables", "Practical webinars and talks"] },
  { slug: "our-impact", name: "Our impact", title: "Technology should leave people and systems stronger.", intro: "We measure impact in more than launches: stronger teams, more resilient systems, better decisions, and value that compounds over time.", body: "Our approach is designed to make improvement sustainable. We reduce unnecessary complexity, make operational knowledge visible, and help teams create habits that continue after an engagement ends.", points: ["Capability transferred to internal teams", "More reliable and observable platforms", "Reduced delivery friction and rework", "Technology decisions tied to measurable outcomes"] },
  { slug: "press-kit", name: "Press kit", title: "The Hill-Top Consultancy story, ready to share.", intro: "Brand assets, company background, leadership information, and approved boilerplate for media and partners.", body: "This page is prepared for the final press kit package, including approved logos, company descriptions, leadership bios, contact details, and downloadable brand assets.", points: ["Company boilerplate and key facts", "Approved logo and visual assets", "Leadership and spokesperson information", "Press and partnership contact details"] },
] as const;

function AboutHeader() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <><header className="inner-header"><a className="wordmark hilltop-wordmark" href="/" aria-label="Hill-Top Consultancy home">Hill-Top Consultancy</a><nav className="desktop-nav inner-nav" aria-label="Primary navigation"><ServicesMegaMenu /><SiteMegaMenu label="About us" href="/about" intro="About Hill-Top" title="A partner built for lasting value." items={aboutItems} /><SiteMegaMenu label="Industries" href="/industries" intro="Industries we serve" title="Deep context. Better outcomes." items={industryItems} /><a href="/insights">Success stories</a><a href="/insights">Insights <ChevronDown size={15} /></a></nav><div className="inner-header-actions"><a className="contact-button inner-contact" href="/contact">Contact us</a><button className="icon-button inner-menu-button" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu size={24} /></button></div></header>{menuOpen && <div className="inner-menu"><button className="inner-menu-close" onClick={() => setMenuOpen(false)}>×</button><p className="eyebrow">Hill-Top Consultancy</p>{[['Services','/services'],['Industries','/industries'],['About Hill-Top','/about'],['Insights','/insights'],['Contact','/contact']].map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={20} /></a>)}</div>}</>;
}

function AboutLayout({ children }: { children: React.ReactNode }) { return <div className="about-page"><AboutHeader />{children}</div>; }

export function AboutOverview() {
  return <AboutLayout><section className="about-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / about us</span><h1>Built for the hard parts of meaningful change.</h1><p>We help ambitious organizations turn technology challenges into lasting business value through senior advice, practical engineering, and teams that stay close to outcomes.</p></div></section><section className="about-overview-body content-width"><div className="about-overview-lead"><div><span className="service-page-kicker">Why Hill-Top</span><h2>Technology is only valuable when people can use it to move forward.</h2></div><p>Our work connects cloud, DevOps, software, data, AI, and security to the decisions your organization has to make. We bring clarity to the next step, then help your teams deliver it with confidence.</p></div><div className="about-principles">{["Clarity before complexity", "Senior people in the room", "Evidence over theatre", "Capability that stays with you"].map((item, index) => <article key={item}><b>0{index + 1}</b><h3>{item}</h3><p>We make the important thing visible, practical, and connected to the outcome it is meant to create.</p></article>)}</div><div className="about-story"><div><span className="service-page-kicker">Our story</span><h2>A focused partner for teams that need progress, not more noise.</h2></div><div><p>Hill-Top Consultancy brings together strategy, engineering, and operational thinking so change can survive contact with the real world. We start with context, work in increments, and leave behind stronger systems and stronger teams.</p><a className="orange-cta" href="/about/company-overview">Read the company overview <ArrowUpRight size={15} /></a></div></div><div className="about-section-links">{aboutSections.map((section) => <a href={`/about/${section.slug}`} key={section.slug}><span>{section.name}</span><ArrowRight size={17} /></a>)}</div></section></AboutLayout>;
}

export function AboutSectionPage({ slug }: { slug: string }) {
  const section = aboutSections.find((item) => item.slug === slug) ?? aboutSections[0];
  return <AboutLayout><section className="about-hero about-section-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / about us</span><h1>{section.title}</h1><p>{section.intro}</p></div></section><section className="about-section-body content-width"><div className="about-section-lead"><div><span className="service-page-kicker">{section.name}</span><h2>How we think about {section.name.toLowerCase()}.</h2></div><p>{section.body}</p></div><div className="about-points"><h3>What matters to us</h3><ul>{section.points.map((point) => <li key={point}><Check size={17} />{point}</li>)}</ul></div><div className="about-page-cta"><div><span className="service-page-kicker">Hill-Top Consultancy</span><h2>Make the next step easier to see.</h2></div><a className="orange-cta" href="/contact">Start a conversation <ArrowUpRight size={15} /></a></div></section></AboutLayout>;
}

export function AboutRouter() {
  const [, params] = useRoute("/about/:slug");
  return params ? <AboutSectionPage slug={params.slug} /> : <AboutOverview />;
}
