import { ArrowRight, ArrowUpRight, Check, ChevronDown, Menu } from "lucide-react";
import GlobalSearch from "@/components/GlobalSearch";
import { useRoute } from "wouter";
import { useState } from "react";
import ServicesMegaMenu from "@/components/ServicesMegaMenu";
import SiteMegaMenu, { aboutItems, industryItems } from "@/components/SiteMegaMenu";

const industries = [
  { slug: "finance", name: "Finance", title: "Build trust into every financial experience.", intro: "Secure, resilient technology for institutions balancing customer expectations, regulation, data, and constant change.", detail: "Finance teams need platforms that protect sensitive information while making room for faster decisions, better service, and more efficient operations. Hill-Top Consultancy connects cloud, data, software, and security around that balance.", capabilities: ["Secure digital banking and customer platforms", "Data governance, analytics, and decision support", "Cloud modernization with regulatory guardrails", "Risk, resilience, and application security"], outcomes: ["More resilient customer journeys", "Clearer risk and compliance visibility", "Faster product and service iteration"] },
  { slug: "retail", name: "Retail", title: "Create retail experiences that keep pace with demand.", intro: "Connected commerce, customer, and operational platforms for retailers that need speed without sacrificing reliability.", detail: "From digital storefronts to inventory, pricing, fulfillment, and loyalty, retail performance depends on many systems working together. We help teams create the architecture and delivery discipline to make that complexity manageable.", capabilities: ["Commerce and customer experience platforms", "Personalization and recommendation data", "Inventory, order, and fulfillment integration", "Cloud scale, observability, and release automation"], outcomes: ["More dependable peak-season performance", "Faster experimentation and releases", "Better visibility across customer and operational data"] },
  { slug: "healthcare", name: "Healthcare", title: "Technology that supports better care and better operations.", intro: "Secure, human-centered digital systems for providers, health platforms, and medical technology teams.", detail: "Healthcare technology has to work for clinicians, patients, administrators, and compliance teams at once. We focus on usable experiences, trusted data, resilient integrations, and security practices that respect the sensitivity of the domain.", capabilities: ["Patient and clinician digital experiences", "Interoperability and healthcare integrations", "Data platforms and secure analytics", "Medical, operational, and connected-device software"], outcomes: ["Less friction in care workflows", "More reliable access to trusted information", "Stronger privacy and security foundations"] },
  { slug: "manufacturing", name: "Manufacturing", title: "Connect the factory, the product, and the future.", intro: "Industrial software, IoT, data, and cloud foundations that help manufacturers make operations more visible and responsive.", detail: "Manufacturing organizations need technology that respects the physical world: uptime, safety, equipment, plants, quality, and supply chains. We connect operational priorities to dependable digital platforms and usable data.", capabilities: ["Industrial IoT and edge platforms", "Predictive maintenance and quality analytics", "MES, ERP, and shop-floor integration", "Cloud modernization for operational systems"], outcomes: ["Improved production visibility", "Faster response to quality and equipment signals", "More connected and scalable operations"] },
  { slug: "telecom", name: "Telecom", title: "Engineer the platforms behind always-on connection.", intro: "Scalable, observable systems for communications providers managing high volume, complex networks, and demanding customer expectations.", detail: "Telecom platforms must process large event volumes, integrate across legacy and modern systems, and stay reliable under constant demand. We bring platform engineering, automation, data, and security together for that environment.", capabilities: ["Customer and service management platforms", "Network data and operational automation", "High-volume cloud-native services", "Observability, reliability, and security engineering"], outcomes: ["More reliable service operations", "Faster rollout of new capabilities", "Better customer and network intelligence"] },
  { slug: "energy-and-utilities", name: "Energy & Utilities", title: "Make critical infrastructure smarter and more resilient.", intro: "Digital platforms and data capabilities for organizations managing essential resources, infrastructure, and the transition to a more connected energy future.", detail: "Energy and utility organizations balance reliability, regulation, field operations, assets, customers, and sustainability. We help create secure digital foundations for better visibility, automation, and informed decisions.", capabilities: ["Asset and field-service platforms", "IoT telemetry and operational data", "Customer, billing, and engagement systems", "Resilience, security, and cloud modernization"], outcomes: ["Better asset and field visibility", "More responsive customer operations", "Stronger foundations for modernization"] },
  { slug: "logistics-and-supply-chain", name: "Logistics & Supply Chain", title: "Turn movement and complexity into an advantage.", intro: "Connected software, data, and automation for supply chains that need more visibility, resilience, and speed.", detail: "Logistics performance depends on decisions across routes, inventory, fleets, warehouses, suppliers, and customers. We help teams connect data and workflows so they can respond to change with greater confidence.", capabilities: ["Transportation and fleet platforms", "Warehouse and supply-chain visibility", "Optimization, forecasting, and analytics", "Integration across partners and operational systems"], outcomes: ["Faster planning and exception handling", "Lower operational friction", "More accurate, connected supply-chain decisions"] },
  { slug: "automotive", name: "Automotive", title: "Build connected experiences for a changing mobility world.", intro: "Software, embedded, data, and cloud expertise for automotive organizations moving toward connected products and intelligent operations.", detail: "Automotive teams are redesigning products, factories, ownership experiences, and data models at the same time. We support the engineering foundations that make connected mobility reliable, secure, and useful.", capabilities: ["Connected vehicle and embedded software", "Mobility and customer platforms", "Manufacturing and supply-chain systems", "Data, AI, and cloud engineering"], outcomes: ["Faster connected-product development", "More reliable digital experiences", "Better use of vehicle and operational data"] },
  { slug: "agritech", name: "Agritech", title: "Use data and technology to make growing more intelligent.", intro: "Practical digital tools for agricultural organizations working with equipment, field data, sustainability, and changing conditions.", detail: "Agritech solutions operate across physical environments, seasonal cycles, connectivity constraints, and many sources of field and operational data. We help teams create technology that is usable, resilient, and ready to scale.", capabilities: ["Connected equipment and field telemetry", "Decision support and predictive analytics", "Farm, supply, and traceability platforms", "Mobile and offline-capable experiences"], outcomes: ["Better visibility across field operations", "More informed planning and resource use", "Technology that fits real-world conditions"] },
  { slug: "game-development", name: "Game Development", title: "Create worlds players want to return to.", intro: "Engineering, platform, and immersive technology expertise for game teams building memorable player experiences.", detail: "Great games need compelling interaction and dependable technology underneath. We support teams across gameplay systems, services, performance, tooling, and connected experiences from prototype through live operation.", capabilities: ["Gameplay and systems engineering", "Multiplayer and backend services", "Performance and platform optimization", "AR, VR, and immersive experiences"], outcomes: ["More stable player experiences", "Faster iteration across teams", "A stronger technical foundation for launch and live operations"] },
] as const;

function IndustryHeader() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <><header className="inner-header"><a className="wordmark hilltop-wordmark" href="/" aria-label="Hill-Top Consultancy home">Hill-Top Consultancy</a><nav className="desktop-nav inner-nav" aria-label="Primary navigation"><ServicesMegaMenu /><SiteMegaMenu label="About us" href="/about" intro="About Hill-Top" title="A partner built for lasting value." items={aboutItems} /><SiteMegaMenu label="Industries" href="/industries" intro="Industries we serve" title="Deep context. Better outcomes." items={industryItems} /><a href="/success-stories">Success stories</a><a href="/insights">Insights <ChevronDown size={15} /></a></nav><div className="inner-header-actions"><GlobalSearch /><a className="contact-button inner-contact" href="/contact">Contact us</a><button className="icon-button inner-menu-button" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu size={24} /></button></div></header>{menuOpen && <div className="inner-menu"><button className="inner-menu-close" onClick={() => setMenuOpen(false)}>×</button><p className="eyebrow">Hill-Top Consultancy</p>{[['Services','/services'],['Industries','/industries'],['About Hill-Top','/about'],['Success stories','/success-stories'],['Insights','/insights'],['Contact','/contact']].map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={20} /></a>)}</div>}</>;
}

function IndustryLayout({ children }: { children: React.ReactNode }) { return <div className="industry-page"><IndustryHeader />{children}</div>; }

export function IndustriesOverview() {
  return <IndustryLayout><section className="industry-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / industries</span><h1>Technology shaped by the work your industry demands.</h1><p>We deliver real value to clients because we understand the environments in which they operate: the pressures, regulations, workflows, customers, and systems that make each industry different.</p></div></section><section className="industry-body content-width"><div className="industry-value"><div><span className="service-page-kicker">Value we deliver</span><h2>Deep knowledge creates better technology decisions.</h2></div><p>Our teams combine engineering depth with domain context. We take time to understand how value is created, where risk accumulates, and which changes will make the biggest practical difference. That is how we create platforms and products people can actually use.</p></div><div className="industry-list-header"><span className="service-page-kicker">Industries we serve</span><p>Explore the contexts where Hill-Top Consultancy helps teams modernize, connect, and scale.</p></div><div className="industry-grid">{industries.map((industry, index) => <a href={`/industries/${industry.slug}`} key={industry.slug}><span>0{index + 1}</span><strong>{industry.name}</strong><ArrowRight size={18} /></a>)}</div><div className="industry-feature"><div><span className="service-page-kicker">Expert blog</span><h2>Data sovereignty: What does compliance require in 2026?</h2></div><a className="orange-cta" href="/insights">Read the insight <ArrowUpRight size={15} /></a></div><div className="industry-contact"><div><span className="service-page-kicker">Connect with our experts</span><h2>Bring your industry challenge to the table.</h2></div><a className="orange-cta" href="/contact">Get in touch <ArrowUpRight size={15} /></a></div></section></IndustryLayout>;
}

export function IndustryDetailPage({ slug }: { slug: string }) {
  const industry = industries.find((item) => item.slug === slug) ?? industries[0];
  return <IndustryLayout><section className="industry-hero industry-detail-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / industries</span><h1>{industry.title}</h1><p>{industry.intro}</p></div></section><section className="industry-detail-body content-width"><div className="industry-value"><div><span className="service-page-kicker">{industry.name}</span><h2>Domain context that makes technology more useful.</h2></div><p>{industry.detail}</p></div><div className="industry-detail-columns"><section><h3>Where we help</h3><ul>{industry.capabilities.map((item) => <li key={item}><Check size={16} />{item}</li>)}</ul></section><section><h3>Value to expect</h3><ul>{industry.outcomes.map((item) => <li key={item}><Check size={16} />{item}</li>)}</ul></section></div><div className="industry-detail-cta"><div><span className="service-page-kicker">Connect with our experts</span><h2>Start with the work that matters most.</h2></div><a className="orange-cta" href="/contact">Get in touch <ArrowUpRight size={15} /></a></div></section></IndustryLayout>;
}

export function IndustryRouter() {
  const [, params] = useRoute("/industries/:slug");
  return params ? <IndustryDetailPage slug={params.slug} /> : <IndustriesOverview />;
}
