import { ArrowRight, ArrowUpRight, Check, ChevronDown, Menu } from "lucide-react";
import LogoLockup from "@/components/LogoLockup";
import SiteFooter from "@/components/SiteFooter";
import GlobalSearch from "@/components/GlobalSearch";
import { useRoute } from "wouter";
import { FormEvent, useMemo, useState } from "react";
import ServicesMegaMenu from "@/components/ServicesMegaMenu";
import SiteMegaMenu, { aboutItems, industryItems } from "@/components/SiteMegaMenu";

const insights = [
  { slug: "self-improving-ai-businesses", category: "AI", date: "16 September 2026", updated: "16 September 2026", read: "9 min read", author: "Mara Jensen", authorRole: "AI Strategy Lead", pdf: "/manus-storage/insight-self-improving-ai_bf0e9351.pdf", title: "Self-improving AI: How it works and what it means for businesses", excerpt: "The next generation of AI systems will not only answer questions. They will learn from outcomes, improve their workflows, and change how organizations design operations.", lead: "Self-improving AI is best understood as a managed learning loop rather than a magic property of a model. The system observes what happened, evaluates the result against a goal, identifies a better path, and uses that evidence to improve future decisions. For businesses, the opportunity is significant—but only when the loop is bounded by clear objectives, reliable data, human accountability, and measurable operational outcomes.", sections: [{ heading: "From static automation to learning workflows", body: "Traditional automation follows a defined path. A self-improving system adds feedback: it measures whether the path worked, learns from exceptions, and adjusts within an approved range. That distinction matters because the value comes from the operating loop around the model, not only from the model itself." }, { heading: "The foundations businesses need", body: "Organizations need observable workflows, trustworthy data, explicit success measures, and a way to review model behavior. Without these foundations, improvement becomes anecdotal. With them, teams can separate genuine learning from random variation and make responsible decisions about where autonomy belongs." }, { heading: "Where to start", body: "Start with a workflow that has a clear outcome, meaningful repetition, and a review mechanism. Customer-support routing, document processing, developer assistance, and operational triage are useful candidates because their inputs and outputs can be measured. Prove the feedback loop before expanding the autonomy of the system." }], takeaways: ["Define the outcome before selecting the model.", "Treat evaluation and observability as product capabilities.", "Give systems bounded authority and clear escalation paths.", "Scale only after the improvement loop is repeatable."] },
  { slug: "ai-agent-harness-reliable-2026", category: "AI", date: "15 September 2026", updated: "15 September 2026", read: "11 min read", author: "Leon Okafor", authorRole: "Principal AI Engineer", pdf: "/manus-storage/insight-ai-agent-harness_9c77c3a0.pdf", title: "AI agent harness: What makes agents reliable in 2026", excerpt: "Reliable agents are not produced by prompts alone. They need a harness that controls tools, memory, evaluation, permissions, and recovery.", lead: "An AI agent harness is the engineering system around an agent that makes its behavior observable, testable, and safe to operate. It includes the tools the agent can call, the context it can access, the policies it must follow, the checks applied to its outputs, and the recovery path when something goes wrong.", sections: [{ heading: "The five control surfaces", body: "A useful harness controls identity, tools, context, evaluation, and recovery. Identity determines what the agent is allowed to do. Tools determine how it can act. Context determines what it knows. Evaluation determines whether the result is acceptable. Recovery determines what happens when the plan fails or the environment changes." }, { heading: "Reliability is a system property", body: "A model can be capable and still produce an unreliable agent if tool responses are ambiguous, state is lost, permissions are too broad, or failures are invisible. Reliability comes from composing small, inspectable controls: typed tool contracts, explicit state transitions, idempotent actions, timeouts, and human review for consequential steps." }, { heading: "A practical evaluation loop", body: "Build a scenario set from real work, not only synthetic examples. Capture the input, plan, tool calls, intermediate decisions, final result, and any human correction. Evaluate task completion, policy compliance, efficiency, and user trust. Repeat the loop whenever the model, tools, data, or business process changes." }], takeaways: ["Design the harness before increasing agent autonomy.", "Make every tool call inspectable and permissioned.", "Evaluate complete trajectories, not only final answers.", "Keep a human path for uncertainty and high-impact actions."] },
  { slug: "cloud-maturity-checklist", category: "Cloud & DevOps", date: "12 September 2026", updated: "12 September 2026", read: "8 min read", author: "Sofia Lind", authorRole: "Cloud Transformation Director", pdf: "/manus-storage/insight-cloud-maturity_f11015ed.pdf", title: "The cloud maturity checklist: Signals your platform is ready for growth", excerpt: "Cloud maturity is not the number of services you run. It is the confidence with which your teams can change, operate, and recover.", lead: "Cloud maturity is the ability to make useful changes safely and repeatedly while keeping cost, security, reliability, and developer experience visible. A mature platform does not remove complexity; it creates clear paths through it. The checklist below helps leaders identify whether their foundations support the next stage of growth.", sections: [{ heading: "Delivery is repeatable", body: "Teams should be able to build, test, and deploy through a known path with as little manual coordination as the risk profile allows. Repeatability does not mean every service has an identical pipeline. It means the important controls are consistent, discoverable, and owned." }, { heading: "Operations are observable", body: "A platform is not mature if teams learn about failures from customers. Logs, metrics, traces, alerts, dashboards, and runbooks should connect to service ownership and business impact. The goal is not more telemetry; it is faster understanding and better decisions." }, { heading: "Security and cost are designed in", body: "Identity, network boundaries, data protection, vulnerability management, and cost visibility should be part of the platform experience. When these concerns arrive only as late-stage reviews, teams experience them as blockers instead of design inputs." }], takeaways: ["Measure the path from change to outcome.", "Make ownership and operational context visible.", "Create paved roads without hiding important trade-offs.", "Treat security and cost as engineering concerns from the start."] },
  { slug: "data-sovereignty-compliance-2026", category: "Security & Governance", date: "10 September 2026", updated: "10 September 2026", read: "10 min read", author: "David Mensah", authorRole: "Security & Governance Partner", pdf: "/manus-storage/insight-data-sovereignty_82d40fd1.pdf", title: "Data sovereignty: What does compliance require in 2026?", excerpt: "Data sovereignty is becoming an architecture, operating-model, and supplier-management decision—not a checkbox at the end of a cloud project.", lead: "Data sovereignty asks where information is stored, where it is processed, who can access it, which laws apply, and how an organization can prove its controls work. In 2026, compliance expectations increasingly reach beyond physical location. They include operational access, subcontractors, resilience, encryption, portability, and the ability to respond to changing regulatory requirements.", sections: [{ heading: "Start with classification and purpose", body: "Not every dataset needs the same residency or control model. Classify data by sensitivity, regulatory obligations, business criticality, and legitimate use. Then connect each class to approved locations, processing patterns, retention rules, access policies, and recovery expectations." }, { heading: "Sovereignty is also about people and operations", body: "A database may be located in an approved region while support access, logs, backups, analytics, or managed services introduce a different jurisdictional exposure. Teams need an end-to-end map of data flows and operational access, including the practical realities of incident response." }, { heading: "Design for evidence", body: "Compliance becomes easier when architecture produces evidence as a by-product. Centralized identity, policy-as-code, audit trails, key management, asset inventories, and tested recovery procedures make it possible to answer questions with confidence instead of assembling a response manually under pressure." }], takeaways: ["Map data flows and access, not only storage regions.", "Match controls to data classification and business purpose.", "Include suppliers, backups, logs, and support operations.", "Build evidence into the platform and delivery workflow."] },
];

function InsightsHeader() { const [menuOpen, setMenuOpen] = useState(false); return <><header className="inner-header"><a className="wordmark hilltop-wordmark" href="/" aria-label="Hill-Top Consultancy home"><LogoLockup variant="dark" /></a><nav className="desktop-nav inner-nav" aria-label="Primary navigation"><ServicesMegaMenu /><SiteMegaMenu label="About us" href="/about" intro="About Hill-Top" title="A partner built for lasting value." items={aboutItems} /><SiteMegaMenu label="Industries" href="/industries" intro="Industries we serve" title="Deep context. Better outcomes." items={industryItems} /><a href="/success-stories">Success stories</a><a href="/insights">Insights <ChevronDown size={15} /></a></nav><div className="inner-header-actions"><GlobalSearch /><a className="contact-button inner-contact" href="/contact">Contact us</a><button className="icon-button inner-menu-button" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu size={24} /></button></div></header>{menuOpen && <div className="inner-menu"><button className="inner-menu-close" onClick={() => setMenuOpen(false)}>×</button><p className="eyebrow">Hill-Top Consultancy</p>{[['Services','/services'],['Industries','/industries'],['About Hill-Top','/about'],['Success stories','/success-stories'],['Insights','/insights'],['Contact','/contact']].map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={20} /></a>)}</div>}</>; }
function InsightsLayout({ children }: { children: React.ReactNode }) { return <div className="insights-page">{children}<SiteFooter /></div>; }

export function InsightsIndex() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [newsletterState, setNewsletterState] = useState<"idle" | "success" | "error">("idle");
  const categories = useMemo(() => ["All", ...Array.from(new Set(insights.map((article) => article.category)))], []);
  const filtered = useMemo(() => insights.filter((article) => {
    const matchesCategory = category === "All" || article.category === category;
    const haystack = `${article.title} ${article.excerpt} ${article.category}`.toLowerCase();
    return matchesCategory && haystack.includes(query.toLowerCase().trim());
  }), [category, query]);
  const submitNewsletter = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = event.currentTarget;
    const email = new FormData(form).get("email");
    if (typeof email === "string" && email.includes("@")) { setNewsletterState("success"); form.reset(); } else setNewsletterState("error");
  };
  return <InsightsLayout><InsightsHeader /><section className="insights-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / expert blog</span><h1>Ideas for making complex technology decisions clearer.</h1><p>Practical perspectives for leaders and engineering teams working across AI, cloud, DevOps, data, security, and sustainable delivery.</p></div></section><section className="insights-body content-width"><div className="featured-insight"><div><span className="insight-category">Featured insight · {insights[0].category}</span><h2>{insights[0].title}</h2><p>{insights[0].excerpt}</p><a className="orange-cta" href={`/insights/${insights[0].slug}`}>Read featured insight <ArrowUpRight size={15} /></a></div><div className="featured-insight-number">01</div></div><div className="insights-heading"><div><span className="service-page-kicker">Latest insights</span><h2>Useful thinking for the next decision.</h2></div><p>Long-form notes from the people helping teams turn technology ambition into operating reality.</p></div><div className="insights-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search insights" aria-label="Search insights" /> <div className="insight-filters">{categories.map((item) => <button className={category === item ? "active" : ""} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div></div><p className="insight-results">Showing {filtered.length} of {insights.length} insights</p><div className="insights-grid">{filtered.map((article, index) => <a className="insight-card" href={`/insights/${article.slug}`} key={article.slug}><div className="insight-card-meta"><span>0{index + 1}</span><span>{article.category}</span></div><div className="insight-date">{article.date} · {article.read}</div><h3>{article.title}</h3><p>{article.excerpt}</p><div className="insight-author">By {article.author} · {article.authorRole}</div><span className="insight-read">Read article <ArrowRight size={16} /></span></a>)}</div><div className="insights-subscribe"><div><span className="service-page-kicker">Stay close to the work</span><h2>Bring clearer thinking to your next technology decision.</h2></div><form className="newsletter-form" onSubmit={submitNewsletter}><label htmlFor="newsletter-email">Monthly insights, no noise.</label><div><input id="newsletter-email" name="email" type="email" placeholder="you@company.com" required /><button className="orange-cta" type="submit">Subscribe <ArrowUpRight size={15} /></button></div>{newsletterState === "success" && <small>Thanks—your subscription request has been received.</small>}{newsletterState === "error" && <small>Please enter a valid email address.</small>}</form></div></section></InsightsLayout>;
}
export function InsightDetail({ slug }: { slug: string }) { const article = insights.find((item) => item.slug === slug) ?? insights[0]; return <InsightsLayout><InsightsHeader /><section className="insights-hero insight-detail-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / {article.category} / {article.date}</span><h1>{article.title}</h1><p>{article.excerpt}</p><div className="insight-detail-meta"><span>{article.read}</span><span>{article.category}</span><span>Published {article.date}</span><span>Updated {article.updated}</span></div></div></section><article className="insight-article content-width"><div className="insight-author-profile"><div className="author-avatar">{article.author.split(" ").map((part) => part[0]).join("")}</div><div><strong>{article.author}</strong><span>{article.authorRole}</span><small>Hill-Top Consultancy · Expert blog</small></div><a className="pdf-link" href={article.pdf} download>Download PDF <ArrowUpRight size={15} /></a></div><div className="insight-article-lead"><span className="service-page-kicker">In perspective</span><p>{article.lead}</p></div><div className="insight-article-layout"><aside><span className="service-page-kicker">Key takeaways</span><ul>{article.takeaways.map((item) => <li key={item}><Check size={16} />{item}</li>)}</ul></aside><div className="insight-article-copy">{article.sections.map((section, index) => <section key={section.heading}><span className="insight-section-number">0{index + 1}</span><h2>{section.heading}</h2><p>{section.body}</p></section>)}</div></div><div className="insight-article-cta"><div><span className="service-page-kicker">Need to apply this thinking?</span><h2>Turn an insight into a practical next step.</h2></div><a className="orange-cta" href="/contact">Talk to Hill-Top <ArrowUpRight size={15} /></a></div></article></InsightsLayout>; }

export function InsightsRouter() { const [, params] = useRoute("/insights/:slug"); return params ? <InsightDetail slug={params.slug} /> : <InsightsIndex />; }
