import { ArrowRight, ArrowUpRight, Check, ChevronDown, Menu } from "lucide-react";
import SiteFooter from "@/components/SiteFooter";
import GlobalSearch from "@/components/GlobalSearch";
import { useRoute } from "wouter";
import { useState } from "react";
import ServicesMegaMenu from "@/components/ServicesMegaMenu";
import SiteMegaMenu, { aboutItems, industryItems } from "@/components/SiteMegaMenu";

const stories = [
  { slug: "ai-engineering-acceleration", label: "AI-Augmented Development", client: "Global SaaS platform", title: "From zero AI adoption to 28% AI-generated code in six weeks.", summary: "How a 250-engineer SaaS organization moved from curiosity to governed, measurable AI-assisted delivery without compromising code quality or team trust.", metrics: [["28%", "AI-generated code in six weeks"], ["42%", "reduction in code review time"], ["250", "engineers enabled"]], tags: ["Software Product Engineering", "AI-Augmented Development", "DevOps"], challenge: "The engineering organization knew AI-assisted development was changing the market, but usage was informal, uneven, and impossible to measure. A few engineers were experimenting with coding assistants while others had concerns about quality, intellectual property, security, and the long-term effect on craft. Leadership needed evidence, not a slide deck: where AI could create value, where it introduced risk, and how to build a repeatable adoption model.", context: "The client operated a mature SaaS platform with multiple product squads, a large shared codebase, and an established release cadence. Speed mattered, but so did review quality, production stability, and the confidence of engineers responsible for critical services. Any intervention had to work inside the existing toolchain and respect the differences between teams, languages, repositories, and delivery workflows.", approach: ["Baseline the current delivery system: cycle time, review time, defect signals, test behavior, and developer sentiment.", "Select a small set of representative teams and workflows rather than rolling out a tool indiscriminately.", "Create guardrails for sensitive code, data handling, review ownership, and acceptable AI-assisted changes.", "Instrument adoption and quality together so increased generation did not hide increased rework.", "Document patterns, anti-patterns, and enablement materials that internal platform and engineering leaders could own."], delivery: ["Discovery interviews and repository analysis", "AI workflow design across coding, testing, documentation, and DevOps", "Pilot enablement with selected product squads", "Review policy, security guardrails, and measurement model", "Leadership readout with scale roadmap and investment options"], outcomes: ["AI-assisted coding became visible as an engineering capability rather than an individual experiment.", "Teams reduced time spent preparing and reviewing routine changes while preserving human ownership of decisions.", "Leaders gained a fact base for expanding the program based on delivery signals, not enthusiasm alone.", "The client left with an adoption playbook that could be reused across teams and repositories."] },
  { slug: "transportation-delivery-modernization", label: "Cloud & DevOps", client: "US transportation company", title: "27% higher velocity with 70% faster hotfix deployment.", summary: "How a transportation business improved release confidence by connecting platform foundations, test automation, and practical engineering standards.", metrics: [["27%", "increase in delivery velocity"], ["55% → 81%", "test coverage improvement"], ["70%", "faster hotfix deployment"]], tags: ["DevOps", "Cloud Infrastructure Management", "QA automation"], challenge: "The company was delivering important software into a time-sensitive operational environment, but releases were slowed by manual coordination, uneven test coverage, and a growing fear of hotfixes. Teams knew the bottlenecks, yet each attempt to improve delivery created another layer of process rather than a simpler path to production.", context: "The environment included customer-facing workflows, integrations with operational systems, and services with different reliability requirements. The goal was not to chase an abstract deployment frequency target. It was to make change safer, make feedback faster, and give engineers a clear operating model for regular delivery and urgent fixes.", approach: ["Map the journey from committed change to production signal and identify the highest-friction handoffs.", "Separate platform constraints from team habits so the roadmap addressed causes instead of symptoms.", "Prioritize automated testing around the highest-risk paths and the failure modes that mattered operationally.", "Introduce pipeline standards, deployment controls, and observability patterns that teams could adopt incrementally.", "Use a staged rollout with visible measures for velocity, test confidence, and recovery time."], delivery: ["Value-stream and release-process assessment", "CI/CD workflow redesign and pipeline standardization", "Test strategy, automation, and coverage improvement", "Operational dashboards, alerts, and runbook design", "Team coaching and handover to engineering owners"], outcomes: ["Release work became more predictable because the path to production was easier to understand and repeat.", "Higher automated coverage increased confidence in changes without turning testing into a separate queue.", "Hotfixes moved through a controlled, observable path instead of relying on heroics and manual coordination.", "The organization created a foundation for further cloud modernization and platform enablement."] },
  { slug: "housing-platform-reliability", label: "Quality Engineering", client: "Housing management platform", title: "Regression testing from three days to four hours.", summary: "How a housing platform improved release confidence, shortened incident resolution, and created a sustainable quality operating model for 150+ engineers.", metrics: [["3 days → 4 hours", "regression testing time"], ["87.5%", "reduction in incident resolution time"], ["150+", "engineers supported"]], tags: ["QA automation", "Application Modernization", "AI & Machine Learning"], challenge: "A fast-growing housing management platform had accumulated a large and valuable test estate, but regression testing had become a release event that consumed days. Incidents also took too long to diagnose because ownership, logs, and operational context were distributed across teams and systems.", context: "The platform supported workflows where correctness mattered to residents, property teams, service providers, and internal operations. Quality could not be defined as test pass rate alone. The client needed better risk-based coverage, faster feedback, clearer production signals, and a way to make quality part of everyday delivery.", approach: ["Inventory the test suite and classify coverage by business risk, not only by technical component.", "Identify slow, brittle, and duplicated tests, then redesign the execution strategy around feedback value.", "Connect automated tests with deployment stages so teams received the right signal at the right time.", "Improve observability and incident triage by aligning service ownership, logs, dashboards, and runbooks.", "Create quality standards and coaching loops so improvements continued after the initial engagement."], delivery: ["Quality and test estate assessment", "Regression-suite rationalization and automation", "Test data and environment improvements", "Observability, incident workflow, and runbook design", "Quality enablement for engineering and product teams"], outcomes: ["Regression testing became a four-hour feedback loop rather than a three-day release gate.", "Teams received more useful signals earlier and spent less time maintaining low-value automation.", "Incident resolution improved because production context and ownership were easier to find.", "Quality became a shared engineering responsibility with measurable standards and repeatable practices."] },
];

function StoryHeader() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <><header className="inner-header"><a className="wordmark hilltop-wordmark" href="/" aria-label="Hill-Top Consultancy home">Hill-Top Consultancy</a><nav className="desktop-nav inner-nav" aria-label="Primary navigation"><ServicesMegaMenu /><SiteMegaMenu label="About us" href="/about" intro="About Hill-Top" title="A partner built for lasting value." items={aboutItems} /><SiteMegaMenu label="Industries" href="/industries" intro="Industries we serve" title="Deep context. Better outcomes." items={industryItems} /><a href="/success-stories">Success stories</a><a href="/insights">Insights <ChevronDown size={15} /></a></nav><div className="inner-header-actions"><GlobalSearch /><a className="contact-button inner-contact" href="/contact">Contact us</a><button className="icon-button inner-menu-button" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu size={24} /></button></div></header>{menuOpen && <div className="inner-menu"><button className="inner-menu-close" onClick={() => setMenuOpen(false)}>×</button><p className="eyebrow">Hill-Top Consultancy</p>{[['Services','/services'],['Industries','/industries'],['About Hill-Top','/about'],['Success stories','/success-stories'],['Insights','/insights'],['Contact','/contact']].map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={20} /></a>)}</div>}</>;
}
function StoryLayout({ children }: { children: React.ReactNode }) { return <div className="story-page"><StoryHeader />{children}<SiteFooter /></div>; }

export function StoriesIndex() {
  return <StoryLayout><section className="story-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / success stories</span><h1>Proof that practical engineering changes the numbers.</h1><p>Long-term value is built in the details: the decisions, habits, systems, and teams behind the outcome. Explore how we help organizations move from a difficult starting point to measurable progress.</p></div></section><section className="stories-index-body content-width"><div className="stories-intro"><div><span className="service-page-kicker">Client outcomes</span><h2>Better delivery is not one metric. It is a system of improvements that reinforces itself.</h2></div><p>Our success stories look beyond the launch moment. They show the context, the constraints, the choices, and the operating changes that helped the result last.</p></div><div className="story-cards">{stories.map((story, index) => <a className="story-card" href={`/success-stories/${story.slug}`} key={story.slug}><div className="story-card-top"><span>0{index + 1}</span><span>{story.label}</span></div><h3>{story.title}</h3><p>{story.summary}</p><div className="story-card-metrics">{story.metrics.map(([metric, label]) => <div key={label}><strong>{metric}</strong><span>{label}</span></div>)}</div><span className="story-card-link">Read the full story <ArrowRight size={17} /></span></a>)}</div><div className="stories-cta"><div><span className="service-page-kicker">Your next outcome</span><h2>Make the hard part measurable.</h2></div><a className="orange-cta" href="/contact">Start a conversation <ArrowUpRight size={15} /></a></div></section></StoryLayout>;
}

export function StoryDetail({ slug }: { slug: string }) {
  const story = stories.find((item) => item.slug === slug) ?? stories[0];
  return <StoryLayout><section className="story-hero story-detail-hero"><div className="content-width"><span className="eyebrow light">Hill-Top Consultancy / success stories / {story.label}</span><h1>{story.title}</h1><p>{story.summary}</p><div className="story-tags">{story.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></section><section className="story-detail-body content-width"><div className="story-metric-row">{story.metrics.map(([metric, label]) => <div key={label}><strong>{metric}</strong><span>{label}</span></div>)}</div><div className="story-prose"><article><span className="service-page-kicker">The challenge</span><h2>When the old way of working becomes the constraint.</h2><p>{story.challenge}</p><p>{story.context}</p></article><aside><span className="service-page-kicker">Client context</span><strong>{story.client}</strong><p>Engagement focus: {story.label}</p></aside></div><div className="story-two-column"><section><span className="service-page-kicker">The approach</span><h2>Make the next step clear, then make it repeatable.</h2><ol>{story.approach.map((item, index) => <li key={item}><b>0{index + 1}</b><span>{item}</span></li>)}</ol></section><section><span className="service-page-kicker">What we delivered</span><h2>Work designed to transfer, not create dependency.</h2><ul>{story.delivery.map((item) => <li key={item}><Check size={17} />{item}</li>)}</ul></section></div><section className="story-outcomes"><div><span className="service-page-kicker">The outcome</span><h2>Progress the organization could feel in the work.</h2></div><div>{story.outcomes.map((item) => <p key={item}><Check size={17} />{item}</p>)}</div></section><section className="story-reflection"><span className="service-page-kicker">What made the difference</span><h2>Technology changed because the operating model changed with it.</h2><p>The most durable results came from connecting engineering choices to the way people actually worked. The engagement created shared language, visible measures, and a sequence of improvements that teams could own. That made it possible to keep learning after the initial project ended.</p></section><div className="stories-cta"><div><span className="service-page-kicker">Have a similar challenge?</span><h2>Let’s find the first useful move.</h2></div><a className="orange-cta" href="/contact">Talk to our team <ArrowUpRight size={15} /></a></div></section></StoryLayout>;
}

export function StoriesRouter() { const [, params] = useRoute("/success-stories/:slug"); return params ? <StoryDetail slug={params.slug} /> : <StoriesIndex />; }
