import { ArrowUpRight, Linkedin, Mail, MapPin, Phone } from "lucide-react";
import LogoLockup from "@/components/LogoLockup";

const serviceLinks = [
  ["AI-Augmented Development", "/services/ai-augmented-development-services"],
  ["Cloud Solutions", "/services/cloud-solutions-and-consulting"],
  ["DevOps", "/services/cloud-solutions-and-consulting/devops"],
  ["Data & Analytics", "/services/data-and-analytics"],
  ["AI Consulting", "/services/ai-consulting-and-implementation"],
  ["Security & Quality", "/services/security-and-quality"],
];
const companyLinks = [["About us", "/about"], ["Success stories", "/success-stories"], ["Insights", "/insights"], ["Industries", "/industries"], ["Careers", "/about/careers"], ["Contact us", "/contact"]];

export default function SiteFooter() {
  return <footer className="site-footer"><div className="content-width"><div className="footer-top"><div className="footer-brand"><a className="footer-wordmark" href="/"><LogoLockup compact /></a><p>Pragmatic cloud, DevOps, AI, and software delivery for teams ready to move with confidence.</p><a className="footer-cta" href="/contact">Start a conversation <ArrowUpRight size={15} /></a></div><div className="footer-column"><span>What we do</span>{serviceLinks.map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={13} /></a>)}</div><div className="footer-column"><span>Explore Hill-Top</span>{companyLinks.map(([label, href]) => <a href={href} key={href}>{label}<ArrowUpRight size={13} /></a>)}</div><div className="footer-column footer-contact"><span>Contact Hill-Top Consultancy</span><a href="https://hilltopconsultancy.com" target="_blank" rel="noreferrer"><ArrowUpRight size={14} />hilltopconsultancy.com</a><a href="mailto:contact@hilltopconsultancy.com"><Mail size={14} />contact@hilltopconsultancy.com</a><a href="tel:+4523117908"><Phone size={14} />+45 23 11 79 08</a><a href="https://www.google.com/maps/search/?api=1&query=Sylen%203%2C%202.%20sal%2C%202630%20Taastrup" target="_blank" rel="noreferrer"><MapPin size={14} />Sylen 3, 2. sal<br />2630 Taastrup, Denmark</a><small>CVR 44814544</small><div className="footer-mailboxes"><strong>Email directory</strong><a href="mailto:info@hilltopconsultancy.com">Info · Prince Chafah</a><a href="mailto:contact@hilltopconsultancy.com">Contact · Fafung Sheena</a><a href="mailto:support@hilltopconsultancy.com">Support · Prince Chafah Sani</a><a href="mailto:consult@hilltopconsultancy.com">Consult · Prince Chafah Forchu Sani</a></div></div></div><div className="footer-network"><div><span>Global delivery network</span><strong>10 countries · 13 offices · 2,400+ engineers</strong></div><div className="footer-office-list"><a href="/contact">Denmark</a><a href="/contact">Sweden</a><a href="/contact">United Kingdom</a><a href="/contact">United States</a><a href="/contact">UAE</a><a href="/contact">Singapore</a></div></div><div className="footer-bottom"><span>© 2026 Hill-Top Consultancy · hilltopconsultancy.com</span><div className="footer-legal"><a href="/about/privacy-notice">Privacy Notice</a><a href="/about/terms-conditions">Terms & Conditions</a><a href="/about/cookie-notice">Cookie Notice</a><a href="/about/press-kit">Press kit</a></div><div className="footer-social"><a href="https://www.linkedin.com" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={17} /></a><a href="mailto:contact@hilltopconsultancy.com" aria-label="Email"><Mail size={17} /></a></div></div></div></footer>;
}
